### ISSUE TITLE
there is still no source code. one year later .... 

### ISSUE THREAD

**Issue by nattlip** [athombv/homey-arduino-nrf905#2]

**Comment by Swiftnesses** [comment]
Disappointed this isn't available too, it was one of the reasons I purchased Homey.

**Comment by nattlip** [comment]
The only positive thing is they can but dont , 'They have to use arduino to test the signals for signal 433 898 etc . But indeed selling a geek version without any functionality so far is disappointing. making an app for windows to bypass chrome has priority , i don''t know why, the world is drowning in  apps replacing a browser ie a webpage, that isn't programming , i expect the  app to have extended functionality above a webpage.

**Comment by WeeJeWel** [comment]
@ReinierH has actually started working on this :)

**Comment by nattlip** [comment]
that is a very positve sound and on such short notice.

**Comment by nattlip** [comment]
I must confess , i haven't done any arduino programming yet , i use NETMF on a spider and raptor board, but i can't find any projects whit that system to sniff 433 rf waves, all i found on the internet are arduino / rasberry pie based. I hoped Homey could introduce me to that , homey i think is linux based  rasberry pie with a lot of extra peripherals to communicate on more ways as with a http request  with your equipment.
